Add rmi changes for jpedal microservice
idrsolutions/jpedal-microservice-example pull request #38
Opened 2023-11-28 10:58 UTC by Amy1612

2023-11-28 14:51 UTC, daniel-warren requested changes

2023-11-28 14:51 UTC, daniel-warren commented on src/main/java/com/idrsolutions/microservice/JPedalServlet.java
> +        File output = new File(outputDirStr + fileSeparator + fileNameWithoutExt);
Could this be final?
```suggestion
        final File output = new File(outputDirStr + fileSeparator + fileNameWithoutExt);
```

2023-11-28 14:51 UTC, daniel-warren commented on src/main/java/com/idrsolutions/microservice/JPedalServlet.java
> +        float scaling = (conversionParams.containsKey("scaling") ? Float.parseFloat(conversionParams.get("scaling")) * 1.52f : 1.52f);
Can this be final?
```suggestion
        final float scaling = (conversionParams.containsKey("scaling") ? Float.parseFloat(conversionParams.get("scaling")) * 1.52f : 1.52f);
```

2023-11-28 14:51 UTC, daniel-warren commented on src/main/java/com/idrsolutions/microservice/JPedalServlet.java
> +                String type = conversionParams.get("type");
Thoughts on renaming the variable so it can be final?
```suggestion
                final String imageType = conversionParams.get("type");
```

2023-11-28 14:51 UTC, daniel-warren commented on src/main/java/com/idrsolutions/microservice/JPedalServlet.java
> +                type = conversionParams.get("type");
Thoughts on renaming the variable so it can be final?
```suggestion
                final textType = conversionParams.get("type");
```

2023-11-28 14:51 UTC, daniel-warren commented on src/main/java/com/idrsolutions/microservice/JPedalServlet.java
> +                    }
Could we not simplify this to a single Exception thrown?
Either
```suggestion
                    throw new JPedalServletException("Unrecognised mode specified: " + mode.name());
```
or
```suggestion
                    throw new RuntimeException("Unrecognised mode specified: " + mode.name());
```

2023-11-28 14:51 UTC, daniel-warren commented on src/main/java/com/idrsolutions/microservice/JPedalServlet.java
> +        }
Depending on if / how the try/catch under default is handled, do we still need to keep this class definition?

2023-11-29 11:01 UTC, leonatherton commented on src/main/resources/jpedal-microservice.properties
> +conversionMemoryLimit=3072
In BuildVu/FormVu we have added some extra comments that I think would be nice to add for JPedal too - see
https://github.com/idrsolutions/buildvu-microservice-example/pull/71/files#diff-f16457c3fb10bb8c7bd0fa2b61c911fe755b7a2b2c97a1d0f7e37d8b7e5a0df0

We've also used 1024 for `conversionMemoryLimit` which is probably a more sensible default?

2023-11-29 11:08 UTC, leonatherton commented on src/main/java/com/idrsolutions/microservice/JPedalServlet.java
> +
Do we need to pass the settings from `conversionParam` here ([buildvu example](https://github.com/idrsolutions/buildvu-microservice-example/pull/71/files#diff-4e71fa4ee75caea8eae526fd78fb85013a3f57696e03d289d9c8e38e7120afdeR218-R224)) such as the password?

2023-11-30 16:31 UTC, leonatherton approved these changes

2023-12-01 10:04 UTC, merged