Updated to Java 17
idrsolutions/jpedal-microservice-example pull request #43
Opened 2024-09-27 16:29 UTC by JacobIDR

Quick PR to bump the Java version to match the upcoming JPedal Java version.

2024-09-27 16:33 UTC, leonatherton requested changes

2024-09-27 16:33 UTC, leonatherton commented on pom.xml
> +        <maven.compiler.release>17                                   </maven.compiler.release>
```suggestion
        <maven.compiler.release>17</maven.compiler.release>
```

2024-09-27 16:37 UTC, leonatherton approved these changes

2024-09-30 07:57 UTC, KieranFrance approved these changes

2024-09-30 10:43 UTC, josrepo approved these changes

2024-09-30 12:57 UTC, merged